hub:
  image: selenium/hub:3.14.0-arsenic
  ports:
    - "4444:4444"
firefox:
  image: selenium/node-firefox:3.14.0-arsenic
  links:
    - hub
chrome:
  image: selenium/node-chrome:3.14.0-arsenic
  links:
    - hub
