hub:
  image: selenium/hub:3.141.59-radium
  ports:
    - "4444:4444"

firefox:
  image: selenium/node-firefox:3.141.59-radium
  links:
    - hub

chrome:
  image: selenium/node-chrome:3.141.59-radium
  links:
    - hub
